version: 0.2

phases:
  build:
    commands:
      - echo Building backend...
      - docker build -t backend ./backend
      - docker tag backend:latest 577638398727.dkr.ecr.eu-west-2.amazonaws.com/backend:latest

      - echo Building frontend...
      - docker build -t frontend ./frontend
      - docker tag frontend:latest 577638398727.dkr.ecr.eu-west-2.amazonaws.com/frontend:latest

      - echo Building nginx...
      - docker build -t nginx -f nginx/Dockerfile .
      - docker tag nginx:latest 577638398727.dkr.ecr.eu-west-2.amazonaws.com/nginx:latest

  post_build:
    commands:
      - echo Pushing backend image...
      - docker push 577638398727.dkr.ecr.eu-west-2.amazonaws.com/backend:latest

      - echo Pushing frontend image...
      - docker push 577638398727.dkr.ecr.eu-west-2.amazonaws.com/frontend:latest

      - echo Pushing nginx image...
      - docker push 577638398727.dkr.ecr.eu-west-2.amazonaws.com/nginx:latest

      - echo Generating imagedefinitions.json...
      - echo '[{"name":"nginx","imageUri":"577638398727.dkr.ecr.eu-west-2.amazonaws.com/nginx:latest"},{"name":"frontend","imageUri":"577638398727.dkr.ecr.eu-west-2.amazonaws.com/frontend:latest"},{"name":"backend","imageUri":"577638398727.dkr.ecr.eu-west-2.amazonaws.com/backend:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
