version: 0.2

env:
  variables:
    AWS_REGION: eu-west-2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 577638398727.dkr.ecr.eu-west-2.amazonaws.com

  build:
    commands:
      - echo Building backend...
      - docker build -t backend ./backend
      - docker tag backend:latest 577638398727.dkr.ecr.eu-west-2.amazonaws.com/backend:latest

      - echo Building frontend...
      - docker build -t frontend ./frontend
      - docker tag frontend:latest 577638398727.dkr.ecr.eu-west-2.amazonaws.com/frontend:latest

      - echo Building nginx...
      - docker build -t nginx -f nginx/Dockerfile .
      - docker tag nginx:latest 577638398727.dkr.ecr.eu-west-2.amazonaws.com/nginx:latest

  post_build:
    commands:
      - echo Pushing images to ECR...
      - docker push 577638398727.dkr.ecr.eu-west-2.amazonaws.com/backend:latest
      - docker push 577638398727.dkr.ecr.eu-west-2.amazonaws.com/frontend:latest
      - docker push 577638398727.dkr.ecr.eu-west-2.amazonaws.com/nginx:latest

      - echo Writing imagedefinitions.json...
      - printf '[{"name":"backend","imageUri":"%s"},{"name":"frontend","imageUri":"%s"},{"name":"nginx","imageUri":"%s"}]' \
          577638398727.dkr.ecr.eu-west-2.amazonaws.com/backend:latest \
          577638398727.dkr.ecr.eu-west-2.amazonaws.com/frontend:latest \
          577638398727.dkr.ecr.eu-west-2.amazonaws.com/nginx:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
